// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ5cxqZyLMJ8MX2gU0xGSp_8N5lXgXDkE',
    appId: '1:847073606816:web:d85e0c4fcc96cd4f03ddc5',
    messagingSenderId: '847073606816',
    projectId: 'flappyfire-e4251',
    authDomain: 'flappyfire-e4251.firebaseapp.com',
    storageBucket: 'flappyfire-e4251.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6M97fx40rmf2DhOjcdHe6Qq2ZdSQ5oqw',
    appId: '1:847073606816:android:e90135781b42e11b03ddc5',
    messagingSenderId: '847073606816',
    projectId: 'flappyfire-e4251',
    storageBucket: 'flappyfire-e4251.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1DlNgUBmYzTIKI3Ko085fhm-sNYW3F_c',
    appId: '1:847073606816:ios:5b28c536329f775b03ddc5',
    messagingSenderId: '847073606816',
    projectId: 'flappyfire-e4251',
    storageBucket: 'flappyfire-e4251.appspot.com',
    iosClientId:
        '847073606816-0l0rapub1qtnna7jrklrk2j2r1gdeucs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flap14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1DlNgUBmYzTIKI3Ko085fhm-sNYW3F_c',
    appId: '1:847073606816:ios:5b28c536329f775b03ddc5',
    messagingSenderId: '847073606816',
    projectId: 'flappyfire-e4251',
    storageBucket: 'flappyfire-e4251.appspot.com',
    iosClientId:
        '847073606816-0l0rapub1qtnna7jrklrk2j2r1gdeucs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flap14',
  );
}
